apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
  namespace: default
spec:
  target:
    name: example-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: my-bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        # `key` is actually the `name` of your secret in bitwarden
        key: my-bitwarden-secret-name
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: my-bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: my-bitwarden-secret-name
        property: password
