name: Lint and Test Chart

on:
  pull_request:
    paths:
      - 'charts/**'

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Install Helm
        uses: azure/setup-helm@v3.5

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        id: lint
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install ESO and Vaultwarden dependencies for testing
        run: |
          helm repo add vaultwarden https://jessebot.github.io/vaultwarden
          helm repo add external-secrets https://charts.external-secrets.io
          helm repo update
          helm install vaultwarden vaultwarden/vaultwarden --set domain="https://bw.example.com:8443" --wait
          helm install external-secrets external-secrets/external-secrets
          kubectl port-forward vaultwarden-0 8080:8080 &
          sleep 5
          curl 'http://localhost:8080/identity/accounts/register' -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/116.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: http://localhost:8080/' -H 'content-type: application/json; charset=utf-8' -H 'device-type: 10' -H 'Bitwarden-Client-Name: web' -H 'Bitwarden-Client-Version: 2023.5.0' -H 'Origin: http://localhost:8080' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-raw '{"email":"test@test.com","name":"test","masterPasswordHash":"gwzxysy3w8OF78wr9Ui9ej2j+34LMQDIK1L97GDWHcE=","key":"2.m1Pc7VH1kfasfCocobb//w==|2/kAMmyg2lExmXc924iv4JwIHXQBbUJnkJcuA0hRzNQb5ercOZQIZsEe73n6AbKolzy5HNR7fNGmdomnahThjvmaxp0knZgFCWNXlXxdruE=|CtHjloKRalKcbvzQSIGdEAj2dKdZQKJ+WYvEeIT82JY=","referenceData":{"id":null},"captchaResponse":null,"kdf":0,"kdfIterations":600000,"masterPasswordHint":"the meepmoopmeep","keys":{"publicKey":"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA29h2aQ6acw87/W5mSYePZvRcaC11lvQlKqJp9bbPSxZ0gkjSt6gIRTg6UWruSUJUWJxYXXjit/Gd/l0iRm2sKtQ/jNs3wsRKdnDaeQD38HEeFHP/CDRZIx05AApRjJ78Cuj+qYau8i4pHQg2hSfDgpkojm19YjjoCSpAj8lc4LdhmyFx7oObS2VDvAccjiMK3XBLDJ9DmQiNFAIVjIah/0yFrSYeiEq8MtUj+CfZ/kcZcClRjtnWjDs054cfQkW3PSvRAWjCaS6+Kq7IZuph+4SOs6m5I52FnyoG75cQ3+JG7NRRm5rqvhN+tur3GWavGnW47a5bF18aHD+y6CARGwIDAQAB","encryptedPrivateKey":"2.OtO4rKuIMHKEQhOl4Lsspg==|huUizgEcIlhd5Mb+2VWbAkPLjvyEHGK9INHoZFkjZaQD50aaxTg6xIb/AjOI0/YL4AxMPspU1S/SBY2qCfIxH6rwPNrtr26Ex/ev669edENPEOkkPp/phApD5weVcQqUAHdjdU6pTGHNFWibQfNpDnzetE6WzuBFY9bqZP2jMYFQABQJxAw0F2FpWjphEvRWR7CsCQ891CPt3xBxSzjKEZ+rSejDyHGeuFSi5huTona52WFvqJYf2zb0okM2FvHh6Edw1pFZ3u+B0+nNh7wSQvLtM44Ug7aD8PMLlHWtzMlNj+gpfR/P1uKmG3qZav84xO4WcCbvShzrt4eylgcKVbJpL880jIPeY4gfL4/C7aFrfEHpkO2mg8Ir2CMefvYH6o/RK7MWkKmJZAxgm71QzVEBxxwpM20tMDdaFD7qYe0QRI0Wj6ktN2AnTBPBs9VhkEcWQA8L3sypjRFV5ZgMB6ZCna18h2WvyDXNiD5gII1Roz7gtipoDXsuvE5/mTCTRYm7wgiAmLlcsG9wIb1wpKpVh+3+egv/LPWU0UIPjhO4f9hTRQ+t4QCyVep/Wxutqjj2SfgsrXwE98R4NNyavQapeqzzKWSEIunc1m315FvmTHFJAFcE2rPUQdQ37NIUPqdKELwysutaB5VPIahfVW3EqiBPctOaDiZxDWf7/hwRsBP2yQt5PKIlNjtw3I9fZ5STKJfYQ7zZxPNrJ27KOVWzG5BnyB90VHx5iEANZMWJt+PU2K1DF8IczVEizMZlN007U9c0g+vE7NoY8r29QOy1nk0PK0veRjZRlSOcCbY4nbke78ameeV8QvFpUISnYTH2XbGMh2KufFVl5zQjiOXLMLo+K8+XbBo6uzva3VR1ht+IvwQt2B7EDBuM0ErgvKbixMfX4CwUJh5gKQZnjy1AHIP8ofZHsy9eOb0N+MOq8+H0CMcwnIvae/Q6k4Vy+wzgrtFx6dWrUXDy0zYMVHlVhxwv3JGwt55BBNOgAVqk7sK3nxmr4xVEfiv7WoIkzKGqNtlCo9OcImHyMUAfw4MSxccU9fKEggmB7Ud6F6Y9uVGvsNvxZ+1rbzoo3CircW+orBXRCH4D/tYZ/WFNKZkgOruJzByDFx0D1ntHAoKjx2QGrGSnLDKTLlg3BWn8YU2I2Gy5Nce8rdz9zrBJfOXvOZMiZAzAuL39NTfg04VbPtUofKEsqDHy/Sj/nl6PLnEWBFjiWqFkeY1tPvIHSYxg6bcBc6pu6Jxe2R935JHMeF48GlU7hLl+GUUiz6GIWZt5qnLDrCqEqt4aWsO2Yjv87ayM2bffDpDQLokLmPxWzz1gCUUvpod6NBUwjZdY5jyQXSuERuZyQKX9oSLCz+8Gb31lMfUUaif7PvbghKPZ1cQEMWwz6s4k6imFyydukOPwa4RY3wsSM0TOPQnJI3MEyJIl5O79Njt9Q+ko6jOpYSzEwykc1dh/9GL0qsSaPj5Si7y9nTo2xd5ISXm+mOweGo/ayc9N2GBbegyzceJNc/gVSbuCcsKml91IMG4YHzXZ8iNfQoq12EcySEe7ip9r9QxWvqC083wu4puh7AZyVV1GdNUvvGkHZTc73zC8Sb9TjUxLLQ97YoqMb2VTwx8IiwBhtYIcDEWrVSElqnI=|Su7zOvV+Kfs1DOcEtrrz+NaT2xtd/E2vmRNF9JMqZ50="}}'

      - name: Run chart-testing (install)
        id: install
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }} --helm-extra-set-args="--set=bitwarden_eso_provider.auth.host=http://localhost:8080 --set=bitwarden_eso_provider.auth.password=beepboopbeep"
